portals:
  - portalId: 490686
    name: PROD
    authType: oauth2
    auth:
      clientId: 53cc8324-d401-4180-83b3-1a1d9842eae4
      clientSecret: 5399b5f2-cb45-4a34-b025-f1d5baa76a10
      scopes:
        - content
      tokenInfo:
        expiresAt: '2020-01-28T23:04:03.232Z'
        refreshToken: 9d21e3db-56c2-417c-bb10-86fb94ade705
        accessToken: >-
          CL2k7_X-LRICAgEYvvkdIN_3xAMo6Z0MMhkAINpJbFmPOn4yLmHqkSXoaINsT40EtAcIOhEAMQBB_wcAAAAAgAAAYHjDKEIZACDaSWycRBheqLDchBYFl4Bk2YeDCM3kkQ
