defaultPortal: DEV
portals:
  - name: PROD
    portalId: 490686
    authType: oauth2
    auth:
      clientId: 53cc8324-d401-4180-83b3-1a1d9842eae4
      clientSecret: 5399b5f2-cb45-4a34-b025-f1d5baa76a10
      scopes:
        - content
      tokenInfo:
        expiresAt: '2021-02-04T01:07:32.512Z'
        refreshToken: 9d21e3db-56c2-417c-bb10-86fb94ade705
        accessToken: >-
          CPnHm9f2LhICAgEYvvkdIN_3xAMo6Z0MMhkAmmWe68WkbPC2zuW9fvUjd93JkMBO7cbLOiQAMQBB_wcAAAAAgAAAYHjGKAAAACAAAAAUAAAYAAAAwMMfBgFCGQCaZZ7rgeZ1nPbE4SIgKP-LzJl3Wlpwr8A
  - name: DEV
    portalId: 8439350
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPv2r8ylLxIEAA0ADBi2jIMEIN_3xAMo7ukMMhkAoDW7s52fOodgjMkHlbn2pO04RQwdWoj9OigAAARBAAAAeAAAAAAAAAAAgAEAAAAAAATAAMAHYAAAAAAAAAAAAABgQhkAoDW7szQ3mBcigAsp9giR-12mdAgQiPoCSgNuYTE
        expiresAt: '2021-06-29T20:53:03.998Z'
    personalAccessKey: >-
      CiQwZTRjMGZiMy00NWI2LTRlNWYtYTdjMy05NWI1MWM0NzExYTYQtoyDBBjf98QDKhkABeaRggYx5NMe0VEmys6BA090DAoEAW91
