defaultPortal: DEV
portals:
  - name: PROD
    portalId: 490686
    authType: oauth2
    auth:
      clientId: 53cc8324-d401-4180-83b3-1a1d9842eae4
      clientSecret: 5399b5f2-cb45-4a34-b025-f1d5baa76a10
      scopes:
        - content
      tokenInfo:
        expiresAt: '2020-09-21T23:27:53.490Z'
        refreshToken: 9d21e3db-56c2-417c-bb10-86fb94ade705
        accessToken: >-
          CLbIxJrLLhICAgEYvvkdIN_3xAMo6Z0MMhkAfQLvQwy2Ky3TdvgsRYl7CcZvs8h3TT0kOhwAMQBB_wcAAAAAgAAAYHjHKAAAACAAAAAUAAAYQhkAfQLvQygLZsm3EVGStNzCh7WoGO49ygXt
  - name: DEV
    portalId: 8439350
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMyozbPXLhIEAA0ADBi2jIMEIN_3xAMo7ukMMhkAi97nP96vOTItMbQBTaZu9feFFZ5-K8CkOh0AAARBAAAAeAAAAAAAAAAAgAEAAAAAAATAAMAHYEIZAIve5z8b3AxX1PqpXfabuMO8VaAWcumtdw
        expiresAt: '2020-10-29T22:21:11.122Z'
    personalAccessKey: >-
      CiQwZTRjMGZiMy00NWI2LTRlNWYtYTdjMy05NWI1MWM0NzExYTYQtoyDBBjf98QDKhkABeaRggYx5NMe0VEmys6BA090DAoEAW91
